config/routes.rb
OpenYourProject::Application.routes.draw do

  resources :pages, :only => ENV['CREATE_PAGES'] ? %w[ new create index ] : %w[ index ]

  root :to => ENV['CREATE_PAGES'] ? 'pages#new' : 'pages#index'

end

app/models/page.rb
require 'active_model'

class Page
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :url, :username, :topic

  validates_presence_of :url
  validates_length_of :topic, :minimum => 8
  validates_length_of :username, :minimum => 8

  def initialize(attributes = {})
    @attributes  = attributes
    @attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

  def inspect
    inspection = if @attributes
      @attributes.map{ |key, value| "#{key}: #{value}" }.join(", ")
    else
      "not initialized"
    end
    "#<#{self.class} #{inspection}>"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
require 'fedwiki/fork'

class PagesController < ApplicationController
  def new
    if request.host.match /^#{ENV['APP_SUBDOMAIN']}\./
      page_attrs = {
        :url => 'http://en.wikipedia.org/wiki/Technological_singularity',
        :username => 'John Q. Public',
        :topic => 'Singularity',
      } if CONFIG.form_pre_filled
      @page = Page.new(page_attrs || {})
    else
      #port_suffix = request.port == 80 ? '' : ":#{request.port}"
      #redirect "#{request.scheme}://#{APP_SUBDOMAIN}.#{request.host}#{port_suffix}"
      redirect_to "http://enlightenedstructure.org/Software_Zero/"
    end
  end

  def create
    @page = Page.new(params[:page])
    (render :new and return) unless @page.valid?

    html = RestClient.get @page.url
    doc = Nokogiri::HTML(html)
    begin
      page_url = FedWiki.open(doc, @page.url, :username => @page.username, :topic => @page.topic)
      redirect_to page_url
    rescue FedWiki::NoKnownOpenLicense
      @page.errors.add :url, %{Whoops! We couldn't find a <href="http://creativecommons.org/licenses/" target="_blank">Creative Commons license</a> on this page -- No action was taken}
      render :new
    end
  end

  def index
    @viz = :collections
    @json_path = "http://sfw.#{ENV['SFW_BASE_DOMAIN']}/viz/#{@viz}.json"
  end
end



#get '/curators' do
#  @viz = :curators
#  @json_path = "http://sfw.#{ENV['SFW_BASE_DOMAIN']}/viz/#{@viz}.json"
#  haml @viz
#
#  # Code formerly in SFW around splitting out curators and collections:
#  #
#  #
#  #set :minimum_subdomain_length, 8   # This is our application logic
#  #set :maximum_subdomain_length, 63  # This is a hard limit set by internet standards
#  #set :subdomain_pattern, "[a-z0-9][a-z0-9-]{#{settings.minimum_subdomain_length-1},#{settings.maximum_subdomain_length-1}}"
#  #set :curator_subdomain_pattern,             "(#{settings.subdomain_pattern})"
#  #set :curator_collection_subdomain_pattern,  "(#{settings.subdomain_pattern})\\.(#{settings.subdomain_pattern})"
#  #
#  #
#  #curators_hashes = []
#  #curators = {"name" => "", "children" => curators_hashes}
#  #
#  #for each page obj:
#  #  next unless page['site'] && page['site'].match(/^#{settings.curator_collection_subdomain_pattern}\./)
#  #
#  #  collection_subdomain, curator_subdomain = $1, $2
#  #
#  #  curator_hash = curators_hashes.find{ |curator_hash| curator_hash['name'] == curator_subdomain }
#  #  unless curator_hash
#  #    curator_hash = {"name" => curator_subdomain, "children" => []}
#  #    curators_hashes << curator_hash
#  #  end
#
#end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.haml
!!! 5
/[if IEMobile 7] <html class="no-js iem7">
/[if lt IE 9] <html class="no-js lte-ie8">
/[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)] <html class="no-js" lang="en">
%head
  %meta{:charset => "utf-8"}/
  %title Open Your Project

  / Viewport slides: http://t.co/dKP3o1e
  %meta{:content => "True", :name => "HandheldFriendly"}/
  %meta{:content => "320", :name => "MobileOptimized"}/
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %link{:href => "/favicon.png", :rel => "icon"}/
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  / Fonts from Google"s Web font directory at http://google.com/webfonts
  %link{:href => "http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
  %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
%body{:class => 'no-sidebar'}
  %header{:role => "banner"}
    %hgroup
      %h1
        %a{:href => "/"} Open Your Project
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        %span.message
          Shhh... we're in private alpha, keep us a secret
      %h2
        Collaborative sharing for social change projects
  %nav{:role => "navigation"}
    -#%form{:action => "http://google.com/search", :method => "get"}
    -#  %fieldset{:role => "search"}
    -#    %input{:name => "q", :type => "hidden", :value => "site:openyourproject.org"}/
    -#    %input.search{:name => "q", :placeholder => "Search", :results => "0", :type => "text"}/
    %ul.main-navigation
      %li
        %a{:href => "/"} Open Now
      %li
        = link_to 'Collections', pages_path
  #main
    #content
      %div
        %article{:role => "article"}
          = yield

      %aside.sidebar
        %section
        -#%h1 Top Tags
        -##viz-tags
        -#%script{:src => "/javascripts/viz/tags.js", :type => "text/javascript"}
        -#%section
        -#  %h1 Top Collections
        -#  %a{:href=>'/collections'}
        -#    #viz-collections
        -#  %script{:src => "/javascripts/viz/collections.js", :type => "text/javascript"}
        -#%section
        -#  %h1 Tags
        -#  %ul#pages
        -#    %li.post
        -#      %a{:href => "/pub/Human_Potential/index.html"} Human Potential
        -#    %li.post
        -#      %a{:href => "/pub/Open_Source_Transformation/index.html"} Open Source Transformation
        -#    %li.post
        -#      %a{:href => "/pub/Quotations/index.html"} Quotes
        -#    %li.post
        -#      %a{:href => "/pub/Spiritual_Transhumanism/index.html"} Spiritual Transhumanism
        -#    %li.post
        -#      %a{:href => "/pub/The_Trust_Exchange_is_Landing/index.html"} The Trust Exchange is Landing



  %footer
    Free software for the open curation of the
    /%a{:href => 'http://creativecommons.org/about'}
    Creative Commons.&nbsp;

    An
    %a{:href => 'http://enlightenedstructure.org/Software_Zero/'} Enlightened Structure Software Zero
    project,

    powered by
    = succeed "," do
      %a{:href => 'http://fed.wiki.org/view/welcome-visitors/view/smallest-federated-wiki'} Smallest Federated Wiki

    responsive design by
    = succeed "." do
      %a{:href => "http://octopress.org"} Octopress

app/views/layouts/application.html.haml
!!! 5
/[if IEMobile 7] <html class="no-js iem7">
/[if lt IE 9] <html class="no-js lte-ie8">
/[if (gt IE 8)|(gt IEMobile 7)|!(IEMobile)|!(IE)] <html class="no-js" lang="en">
%head
  %meta{:charset => "utf-8"}/
  %title Open Your Project

  / Viewport slides: http://t.co/dKP3o1e
  %meta{:content => "True", :name => "HandheldFriendly"}/
  %meta{:content => "320", :name => "MobileOptimized"}/
  %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
  %link{:href => "/favicon.png", :rel => "icon"}/
  = stylesheet_link_tag    "application", :media => "all"
  = javascript_include_tag "application"
  = csrf_meta_tags

  / Fonts from Google"s Web font directory at http://google.com/webfonts
  %link{:href => "http://fonts.googleapis.com/css?family=PT+Serif:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
  %link{:href => "http://fonts.googleapis.com/css?family=PT+Sans:regular,italic,bold,bolditalic", :rel => "stylesheet", :type => "text/css"}/
%body{:class => 'no-sidebar'}
  %header{:role => "banner"}
    %hgroup
      %h1
        %a{:href => "/"} Open Your Project
        &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
        %span.message
          Shhh... we're in private collabogeek alpha, please tell only the right people...
      %h2
        Collaborative sharing for social change projects
  %nav{:role => "navigation"}
    -#%form{:action => "http://google.com/search", :method => "get"}
    -#  %fieldset{:role => "search"}
    -#    %input{:name => "q", :type => "hidden", :value => "site:openyourproject.org"}/
    -#    %input.search{:name => "q", :placeholder => "Search", :results => "0", :type => "text"}/
    %ul.main-navigation
      - if ENV['CREATE_PAGES']
        %li
          %a{:href => "/"} Open Now
        %li
          = link_to 'Collections', pages_path
  #main
    #content
      %div
        %article{:role => "article"}
          = yield

      %aside.sidebar
        %section
        -#%h1 Top Tags
        -##viz-tags
        -#%script{:src => "/javascripts/viz/tags.js", :type => "text/javascript"}
        -#%section
        -#  %h1 Top Collections
        -#  %a{:href=>'/collections'}
        -#    #viz-collections
        -#  %script{:src => "/javascripts/viz/collections.js", :type => "text/javascript"}
        -#%section
        -#  %h1 Tags
        -#  %ul#pages
        -#    %li.post
        -#      %a{:href => "/pub/Human_Potential/index.html"} Human Potential
        -#    %li.post
        -#      %a{:href => "/pub/Open_Source_Transformation/index.html"} Open Source Transformation
        -#    %li.post
        -#      %a{:href => "/pub/Quotations/index.html"} Quotes
        -#    %li.post
        -#      %a{:href => "/pub/Spiritual_Transhumanism/index.html"} Spiritual Transhumanism
        -#    %li.post
        -#      %a{:href => "/pub/The_Trust_Exchange_is_Landing/index.html"} The Trust Exchange is Landing



  %footer
    Free software for the open curation of the
    -# %a{:href => 'http://creativecommons.org/about'}
    Creative Commons.&nbsp;

    An
    %a{:href => 'http://enlightenedstructure.org/Software_Zero/'} Enlightened Structure Software Zero
    project,

    powered by
    = succeed "," do
      %a{:href => 'http://fed.wiki.org/view/welcome-visitors/view/smallest-federated-wiki'} Smallest Federated Wiki

    responsive design by
    = succeed "." do
      %a{:href => "http://octopress.org"} Octopress

  /
    ENV['RACK_ENV'] = #{ENV['RACK_ENV']}
    Rails.env = #{Rails.env}

app/views/pages/index.html.haml
%h2#viz-collections-full

:javascript
  collections_viz('#{@json_path}');

app/views/pages/new.html.haml
%ul.overview
  %li
    &raquo;
    Transfer any Creative Commons licensed project
    into the Federated Wiki collaboration framework
  %li
    &raquo;
    Others can copy the project,
    contribute ideas
    and make improvements in their copy
  %li
    &raquo;
    The project acts as an idea seed, giving birth
    to trees of remixes, spreading through
    communities and trust networks

.open
  .action
    Enter a Web Page to Open
  = semantic_form_for @page do |f|
    = f.inputs do
      = f.input :url,      :label => false, :placeholder => 'www.change-the-world.org'
      = f.input :username, :label => false, :placeholder => 'Your name'
      = f.input :topic,    :label => false, :placeholder => 'Topic: help categorize this content for yourself and others'
    = f.actions do
      = f.action :submit, :as => :button, :label => 'Open Now'